# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
$LOCAL_REPO = '~/aws-amplify/amplify-ios'

target 'apiList' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for apiList
  pod 'Amplify', :path => $LOCAL_REPO
  pod 'AmplifyPlugins', :path => $LOCAL_REPO
  pod 'AWSPluginsCore', :path => $LOCAL_REPO
  pod 'AmplifyPlugins/AWSAPIPlugin', :path => $LOCAL_REPO


  target 'apiListTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'apiListUITests' do
    # Pods for testing
  end

end
